<?php
add_action( 'acf/include_fields', function () {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key'                   => 'group_66ac748302d63',
		'title'                 => 'Case Study Settings',
		'fields'                => array(
			array(
				'key'               => 'field_66ac7621a192b',
				'label'             => 'Public Title',
				'name'              => 'public_title',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66ac7637a192c',
				'label'             => 'Public Subheadline',
				'name'              => 'public_subheadline',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66ac7483a1923',
				'label'             => 'Client',
				'name'              => 'client',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66ac74d0a1924',
				'label'             => 'Type',
				'name'              => 'type',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => 'What kind of work was done: App development, UX design, etc.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66ac752ca1925',
				'label'             => 'URL',
				'name'              => 'url',
				'aria-label'        => '',
				'type'              => 'url',
				'instructions'      => 'Is there a link to this project that is live? If so, enter that, otherwise, leave blank to omit this.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_66ac7550a1926',
				'label'             => 'Challenge',
				'name'              => 'challenge',
				'aria-label'        => '',
				'type'              => 'wysiwyg',
				'instructions'      => 'Problem we are trying to solve.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
				'delay'             => 0,
			),
			array(
				'key'               => 'field_66ac7565a1927',
				'label'             => 'Project Goals',
				'name'              => 'project_goals',
				'aria-label'        => '',
				'type'              => 'wysiwyg',
				'instructions'      => 'What goals do you aim to hit with this project?',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
				'delay'             => 0,
			),
			array(
				'key'               => 'field_66ac7580a1928',
				'label'             => 'Solution',
				'name'              => 'solution',
				'aria-label'        => '',
				'type'              => 'wysiwyg',
				'instructions'      => 'What solution did we come up with - essentially, explain the project and how it solves our challenge.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
				'delay'             => 0,
			),
			array(
				'key'               => 'field_66ac7597a1929',
				'label'             => 'Results',
				'name'              => 'results',
				'aria-label'        => '',
				'type'              => 'wysiwyg',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
				'delay'             => 0,
			),
			array(
				'key'               => 'field_66ad4d3ec4b24',
				'label'             => 'Card Image',
				'name'              => 'card_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => 'Card image to show on main pages',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'preview_size'      => 'medium',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'project',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'discussion',
			1 => 'comments',
			2 => 'send-trackbacks',
		),
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
	) );
} );
