<?php
add_action( 'acf/include_fields', function () {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key'                   => 'group_66acb9faae656',
		'title'                 => 'Article Settings',
		'fields'                => array(
			array(
				'key'                  => 'field_66acb9fac7185',
				'label'                => 'Author',
				'name'                 => 'author',
				'aria-label'           => '',
				'type'                 => 'user',
				'instructions'         => 'Choose a public author - this allows us to ghost write.',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'role'                 => '',
				'return_format'        => 'object',
				'multiple'             => 0,
				'allow_null'           => 0,
				'bidirectional'        => 0,
				'bidirectional_target' => array(),
			),
			array(
				'key'               => 'field_66acbc1fc7186',
				'label'             => 'Hero Image',
				'name'              => 'hero_image',
				'aria-label'        => '',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
				'preview_size'      => 'medium',
			),
			array(
				'key'               => 'field_66acbcc5c7187',
				'label'             => 'Sub headline',
				'name'              => 'sub_headline',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_66ad4d77c3303',
				'label'             => 'Card Image',
				'name'              => 'card_image',
				'aria-label'        => '',
				'type'              => 'text',
				'instructions'      => 'Image to use to show article on main pages as a preview.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
	) );
} );

