name: Deploy to Server

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Copy files via SSH
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" rsync -avz --delete \
          -e "ssh -p $SSH_PORT -o StrictHostKeyChecking=no" \
          ./  \
          $SSH_USER@$SSH_HOST:/var/www/berylliumstudios.com/wp-content/themes/beryllium
